"""Declarative base, naming conventions, and the mixins every table shares."""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any, ClassVar

from sqlalchemy import DateTime, MetaData, func, text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Postgres generates names for unnamed constraints and indexes, and those names end up
# in migrations. Without a convention, Alembic autogenerate produces a drop of
# "ix_1a2b3c" and a create of something else on a machine where the name differed, and
# the diff is unreviewable. Naming them here makes migrations deterministic.
NAMING_CONVENTION: dict[str, str] = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

#: The vector width every embedding column is declared at. pgvector needs a fixed
#: dimension to build an index, so this cannot be read from configuration at runtime:
#: `EMBEDDING_DIM` is validated against it at startup instead. Changing the model at
#: the same width is a re-embed job; changing the width is a migration and a re-embed.
EMBEDDING_DIM = 768


class Base(DeclarativeBase):
    """Declarative base for every table in the schema."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)

    type_annotation_map: ClassVar[dict[Any, Any]] = {
        dict[str, Any]: JSONB,
        list[str]: JSONB,
    }


def uuid_pk() -> Mapped[uuid.UUID]:
    """Primary key generated by the database, so an insert needs no round trip."""
    return mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )


class TimestampMixin:
    """`created_at` and `updated_at`, both maintained by the database.

    Server-side defaults rather than Python ones, so a row written by a migration, a
    backfill script or psql is stamped the same way as one written by the application.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )


class CreatedAtMixin:
    """`created_at` only, for tables that are append-only."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
