/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * The signed-in user
     * @description Return the caller's account.
     *
     *     The row is created by the `tenant_db` dependency, on whichever request arrives
     *     first. What makes that possible is that the id is derived from the token subject,
     *     so it is known before the row exists — looking the user up by subject would need a
     *     query the row-level security policy on `users` correctly refuses, and the usual
     *     escape from that is a privileged lookup path that bypasses RLS. There isn't one.
     */
    get: operations["me_read_me"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/profile": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * The user's profile
     * @description The profile and every item on it, in display order.
     */
    get: operations["profile_get_profile"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update contact details and summary
     * @description Update the fields a rendered document carries.
     */
    patch: operations["profile_update_profile"];
    trace?: never;
  };
  "/profile/items": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Add an item
     * @description Add one item. Typed by the user, so it is reviewed by definition.
     */
    post: operations["profile_add_item"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/profile/items/{item_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Remove an item */
    delete: operations["profile_delete_item"];
    options?: never;
    head?: never;
    /**
     * Edit an item
     * @description Edit an item, re-embedding it if the text changed.
     *
     *     Editing is also how an imported item gets reviewed: correcting the wording is the
     *     review. Anything the user touches is theirs.
     */
    patch: operations["profile_update_item"];
    trace?: never;
  };
  "/profile/items/review-all": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Accept every imported item
     * @description Mark every item reviewed.
     *
     *     Offered because reviewing forty items one at a time is a real cost, and a user who
     *     trusts the import should be able to say so once. It is an explicit action, not a
     *     default, which keeps the meaning of `reviewed` intact.
     */
    post: operations["profile_review_all"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/profile/import": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Import a resume PDF
     * @description Parse a resume into items for review.
     *
     *     Nothing imported is trusted. Every item arrives unreviewed, is excluded from the
     *     fit score until accepted, and may not be cited by generated content.
     */
    post: operations["profile_import_resume"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/jobs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Postings the user has saved
     * @description Saved postings, newest first.
     */
    get: operations["jobs_list_jobs"];
    put?: never;
    /**
     * Save a posting
     * @description Fetch or accept a posting, store it, and queue it for extraction.
     */
    post: operations["jobs_save_job"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/jobs/{job_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * One posting with its requirements
     * @description A posting, its extracted fields, and every requirement found in it.
     */
    get: operations["jobs_get_job"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/jobs/{job_id}/score": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * How the profile matches this posting
     * @description Score this posting against the caller's reviewed profile items.
     *
     *     Computed on read rather than stored. The inputs change whenever the user edits a
     *     profile item, and a cached score is a number that silently stops matching what it
     *     claims to describe. It is one query.
     */
    get: operations["jobs_get_score"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/jobs/{job_id}/retry": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Try a failed posting again
     * @description Re-queue a posting whose extraction failed.
     *
     *     Writes a fresh `job.ingested` event rather than calling extraction inline, so the
     *     retry takes exactly the path the first attempt took.
     */
    post: operations["jobs_retry_job"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/applications": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * The pipeline
     * @description Every application, grouped by stage.
     */
    get: operations["applications_get_board"];
    put?: never;
    /**
     * Start tracking a posting
     * @description Create an application at `Saved`, with the event that put it there.
     *
     *     The first `stage_events` row has a null `from_stage`. Without it the history would
     *     begin at the first move and the time an application spent in `Saved` — which is the
     *     stage most of them die in — would be unmeasurable.
     */
    post: operations["applications_start_application"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/applications/{application_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** One application with its history */
    get: operations["applications_get_application"];
    put?: never;
    post?: never;
    /**
     * Stop tracking
     * @description Remove an application and its history.
     *
     *     Distinct from withdrawing. Withdrawn is an outcome worth keeping in the funnel;
     *     deletion is for something tracked by mistake.
     */
    delete: operations["applications_delete_application"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/applications/{application_id}/stage": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Move an application
     * @description Move to a new stage, appending the event that records it.
     */
    post: operations["applications_move_stage"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/applications/{application_id}/tailor": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Generate a tailored resume
     * @description Write a resume for this application from reviewed profile items only.
     *
     *     Every bullet is checked against the items it cites before the artifact is stored.
     *     Anything that fails is dropped and the reason is recorded, so the response can be
     *     honest about what is not in the document.
     */
    post: operations["documents_tailor"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/applications/{application_id}/artifacts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Documents generated for an application
     * @description Every version, newest first. Versions are kept so an earlier draft is recoverable.
     */
    get: operations["documents_list_artifacts"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/artifacts/{artifact_id}/pdf": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Download a document
     * @description Render the stored structure to PDF.
     *
     *     Rendered on demand rather than at generation time, so contact details can be
     *     corrected without paying for the document again. This is the only place in the
     *     system where those details are attached to generated text.
     */
    get: operations["documents_download"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/nudges": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Drafted follow-ups
     * @description Follow-ups drafted for applications that have gone quiet. None has been sent.
     */
    get: operations["documents_list_nudges"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/nudges/{nudge_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Edit or dismiss a draft
     * @description Edit the text, mark it sent, or dismiss it.
     *
     *     Marking it sent records an outcome; it does not send anything. The user sends from
     *     their own mail client, which is what makes "nothing is sent on your behalf" a
     *     property of the system rather than a promise in a document.
     */
    patch: operations["documents_update_nudge"];
    trace?: never;
  };
  "/nudges/sweep": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Look for applications that have gone quiet
     * @description Draft a follow-up for every application past its stage threshold.
     *
     *     Safe to call repeatedly: the unique constraint on
     *     `(application_id, stage, stage_entered_at)` means one wait produces one draft, no
     *     matter how many times this runs. In cloud, Cloud Scheduler calls it daily.
     */
    post: operations["documents_sweep"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/healthz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Liveness check
     * @description Report that the process is up.
     *
     *     This never touches the database. A liveness probe that depends on a downstream
     *     service turns one slow dependency into a restart loop across every instance.
     */
    get: operations["health_healthz"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** ApplicationDetail */
    ApplicationDetail: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Job Id
       * Format: uuid
       */
      job_id: string;
      stage: components["schemas"]["Stage"];
      /**
       * Stage Entered At
       * Format: date-time
       */
      stage_entered_at: string;
      /** Notes */
      notes: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Title */
      title: string | null;
      /** Company */
      company: string | null;
      /** Location */
      location: string | null;
      /** Source Url */
      source_url: string | null;
      /** Days In Stage */
      days_in_stage: number;
      /** Is Active */
      is_active: boolean;
      /** Allowed Next */
      allowed_next: components["schemas"]["Stage"][];
      /** History */
      history: components["schemas"]["StageEventOut"][];
    };
    /** ApplicationOut */
    ApplicationOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Job Id
       * Format: uuid
       */
      job_id: string;
      stage: components["schemas"]["Stage"];
      /**
       * Stage Entered At
       * Format: date-time
       */
      stage_entered_at: string;
      /** Notes */
      notes: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Title */
      title: string | null;
      /** Company */
      company: string | null;
      /** Location */
      location: string | null;
      /** Source Url */
      source_url: string | null;
      /** Days In Stage */
      days_in_stage: number;
      /** Is Active */
      is_active: boolean;
      /** Allowed Next */
      allowed_next: components["schemas"]["Stage"][];
    };
    /**
     * ArtifactKind
     * @enum {string}
     */
    ArtifactKind: "resume" | "cover_letter";
    /** ArtifactSummary */
    ArtifactSummary: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Application Id
       * Format: uuid
       */
      application_id: string;
      kind: components["schemas"]["ArtifactKind"];
      /** Version */
      version: number;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Bullet Count */
      bullet_count: number;
      /** Warnings */
      warnings: string[];
    };
    /**
     * Board
     * @description The pipeline, grouped for display.
     *
     *     Terminal stages are separate from the pipeline because they are outcomes rather
     *     than steps, and a board that shows Rejected as a column beside Onsite reads as
     *     somewhere applications are meant to arrive.
     */
    Board: {
      /** Columns */
      columns: components["schemas"]["BoardColumn"][];
      /** Closed */
      closed: components["schemas"]["ApplicationOut"][];
    };
    /** BoardColumn */
    BoardColumn: {
      stage: components["schemas"]["Stage"];
      /** Applications */
      applications: components["schemas"]["ApplicationOut"][];
    };
    /** Body_profile_import_resume */
    Body_profile_import_resume: {
      /**
       * File
       * @description A PDF with a text layer
       */
      file: string;
    };
    /**
     * Coverage
     * @enum {string}
     */
    Coverage: "covered" | "partial" | "missing";
    /**
     * ErrorBody
     * @description The shape of every error response.
     */
    ErrorBody: {
      /** Code */
      code: string;
      /** Detail */
      detail: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * Health
     * @description Liveness response. Deliberately says nothing about dependencies.
     */
    Health: {
      /** Service */
      service: string;
      /** Version */
      version: string;
      /** Environment */
      environment: string;
    };
    /** ImportOut */
    ImportOut: {
      /** Imported */
      imported: number;
      /** Headline */
      headline: string | null;
      /** Needs Review */
      needs_review: number;
    };
    /** ItemIn */
    ItemIn: {
      /** Text */
      text: string;
      /** @default experience_bullet */
      kind: components["schemas"]["ProfileItemKind"];
      /** Organisation */
      organisation?: string | null;
      /** Role */
      role?: string | null;
      /** Started On */
      started_on?: string | null;
      /** Ended On */
      ended_on?: string | null;
    };
    /** ItemOut */
    ItemOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Text */
      text: string;
      kind: components["schemas"]["ProfileItemKind"];
      /** Organisation */
      organisation: string | null;
      /** Role */
      role: string | null;
      /** Started On */
      started_on: string | null;
      /** Ended On */
      ended_on: string | null;
      /** Display Order */
      display_order: number;
      /** Reviewed */
      reviewed: boolean;
      /** Embedded */
      embedded: boolean;
    };
    /** ItemPatch */
    ItemPatch: {
      /** Text */
      text?: string | null;
      kind?: components["schemas"]["ProfileItemKind"] | null;
      /** Organisation */
      organisation?: string | null;
      /** Role */
      role?: string | null;
      /** Started On */
      started_on?: string | null;
      /** Ended On */
      ended_on?: string | null;
      /** Reviewed */
      reviewed?: boolean | null;
    };
    /**
     * JobDetail
     * @description A posting and everything extraction found in it.
     */
    JobDetail: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      status: components["schemas"]["JobStatus"];
      /** Failure Reason */
      failure_reason: string | null;
      source_ats: components["schemas"]["SourceAts"];
      /** Source Url */
      source_url: string | null;
      /** Title */
      title: string | null;
      /** Company */
      company: string | null;
      /** Location */
      location: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Requirement Count */
      requirement_count: number;
      /** Application Id */
      application_id: string | null;
      /** Seniority */
      seniority: string | null;
      /** Remote Policy */
      remote_policy: string | null;
      /** Employment Type */
      employment_type: string | null;
      /** Experience Years Min */
      experience_years_min: number | null;
      /** Experience Years Max */
      experience_years_max: number | null;
      /** Salary Min */
      salary_min: string | null;
      /** Salary Max */
      salary_max: string | null;
      /** Salary Currency */
      salary_currency: string | null;
      /** Hard Skills */
      hard_skills: string[];
      /** Responsibilities */
      responsibilities: string[];
      /** Requirements */
      requirements: components["schemas"]["RequirementOut"][];
    };
    /**
     * JobStatus
     * @description What ingestion has managed so far. Surfaced directly in the interface.
     * @enum {string}
     */
    JobStatus: "queued" | "extracting" | "embedding" | "ready" | "failed";
    /**
     * JobSummary
     * @description One row of the saved list.
     */
    JobSummary: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      status: components["schemas"]["JobStatus"];
      /** Failure Reason */
      failure_reason: string | null;
      source_ats: components["schemas"]["SourceAts"];
      /** Source Url */
      source_url: string | null;
      /** Title */
      title: string | null;
      /** Company */
      company: string | null;
      /** Location */
      location: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Requirement Count */
      requirement_count: number;
      /** Application Id */
      application_id: string | null;
    };
    /**
     * MatchOut
     * @description One requirement and the evidence that answered it.
     */
    MatchOut: {
      /**
       * Requirement Id
       * Format: uuid
       */
      requirement_id: string;
      /** Requirement */
      requirement: string;
      kind: components["schemas"]["RequirementKind"];
      coverage: components["schemas"]["Coverage"];
      /** Similarity */
      similarity: number;
      /** Evidence Item Id */
      evidence_item_id: string | null;
      /** Evidence */
      evidence: string | null;
    };
    /**
     * Me
     * @description The caller's account.
     */
    Me: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Email */
      email: string;
      /** Timezone */
      timezone: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Has Profile */
      has_profile: boolean;
    };
    /** MoveStage */
    MoveStage: {
      to_stage: components["schemas"]["Stage"];
      /** Note */
      note?: string | null;
      /** Occurred At */
      occurred_at?: string | null;
    };
    /** NudgeOut */
    NudgeOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Application Id
       * Format: uuid
       */
      application_id: string;
      stage: components["schemas"]["Stage"];
      state: components["schemas"]["NudgeState"];
      /** Draft Subject */
      draft_subject: string | null;
      /** Draft Body */
      draft_body: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Title */
      title: string | null;
      /** Company */
      company: string | null;
    };
    /**
     * NudgeOutcome
     * @description Recorded after the fact, so nudge usefulness becomes measurable.
     * @enum {string}
     */
    NudgeOutcome: "sent" | "replied" | "no_reply";
    /**
     * NudgeState
     * @enum {string}
     */
    NudgeState: "pending" | "approved" | "edited" | "dismissed" | "snoozed";
    /** NudgeUpdate */
    NudgeUpdate: {
      state?: components["schemas"]["NudgeState"] | null;
      /** Draft Subject */
      draft_subject?: string | null;
      /** Draft Body */
      draft_body?: string | null;
      outcome?: components["schemas"]["NudgeOutcome"] | null;
      /** Snoozed Until */
      snoozed_until?: string | null;
    };
    /**
     * ProfileItemKind
     * @enum {string}
     */
    ProfileItemKind: "experience_bullet" | "project" | "skill" | "education";
    /** ProfileOut */
    ProfileOut: {
      /** Full Name */
      full_name?: string | null;
      /** Contact Email */
      contact_email?: string | null;
      /** Phone */
      phone?: string | null;
      /** Location */
      location?: string | null;
      /** Links */
      links?: string[];
      /** Headline */
      headline?: string | null;
      /** Summary */
      summary?: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Items */
      items: components["schemas"]["ItemOut"][];
      /** Reviewed Count */
      reviewed_count: number;
      /** Unreviewed Count */
      unreviewed_count: number;
    };
    /** ProfileUpdate */
    ProfileUpdate: {
      /** Full Name */
      full_name?: string | null;
      /** Contact Email */
      contact_email?: string | null;
      /** Phone */
      phone?: string | null;
      /** Location */
      location?: string | null;
      /** Links */
      links?: string[];
      /** Headline */
      headline?: string | null;
      /** Summary */
      summary?: string | null;
    };
    /**
     * RequirementKind
     * @enum {string}
     */
    RequirementKind: "must" | "nice";
    /** RequirementOut */
    RequirementOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Text */
      text: string;
      kind: components["schemas"]["RequirementKind"];
      /** Embedded */
      embedded: boolean;
    };
    /**
     * SaveJob
     * @description Either a link to a supported board, or the description text itself.
     */
    SaveJob: {
      /** Url */
      url?: string | null;
      /** Text */
      text?: string | null;
      /** Title */
      title?: string | null;
      /** Company */
      company?: string | null;
    };
    /** SavedJob */
    SavedJob: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      status: components["schemas"]["JobStatus"];
      /** Created */
      created: boolean;
    };
    /**
     * ScoreOut
     * @description The breakdown, and the number computed from it.
     */
    ScoreOut: {
      /**
       * Job Id
       * Format: uuid
       */
      job_id: string;
      /** Score */
      score: number;
      /** Must Total */
      must_total: number;
      /** Must Covered */
      must_covered: number;
      /** Nice Total */
      nice_total: number;
      /** Nice Covered */
      nice_covered: number;
      /** Matches */
      matches: components["schemas"]["MatchOut"][];
      skills: components["schemas"]["SkillsOut"];
      /** Scorable */
      scorable: boolean;
      /** Embedding Model */
      embedding_model: string | null;
    };
    /**
     * SkillEvidence
     * @description A named technology the posting asks for, and the item that proves it.
     */
    SkillEvidence: {
      /** Skill */
      skill: string;
      /** Evidence */
      evidence: string;
      /**
       * Evidence Item Id
       * Format: uuid
       */
      evidence_item_id: string;
    };
    /**
     * SkillsOut
     * @description Named technologies, split by whether the profile can show them.
     *
     *     Separate from the requirement matches because the two behave differently. A
     *     requirement is prose and is compared by meaning; a skill is a token, and a near
     *     miss is a miss — someone who has used Docker has not used Kubernetes.
     */
    SkillsOut: {
      /** Have */
      have: components["schemas"]["SkillEvidence"][];
      /** Lack */
      lack: string[];
      /** Unused */
      unused: string[];
    };
    /**
     * SourceAts
     * @enum {string}
     */
    SourceAts: "greenhouse" | "lever" | "ashby" | "workday" | "linkedin" | "generic" | "pasted";
    /**
     * Stage
     * @description Where an application currently sits.
     * @enum {string}
     */
    Stage:
      | "saved"
      | "applied"
      | "screen"
      | "technical"
      | "onsite"
      | "offer"
      | "rejected"
      | "withdrawn"
      | "ghosted";
    /** StageEventOut */
    StageEventOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      from_stage: components["schemas"]["Stage"] | null;
      to_stage: components["schemas"]["Stage"];
      /**
       * Occurred At
       * Format: date-time
       */
      occurred_at: string;
      /** Note */
      note: string | null;
    };
    /** StartApplication */
    StartApplication: {
      /**
       * Job Id
       * Format: uuid
       */
      job_id: string;
      /** Note */
      note?: string | null;
    };
    /** SweepOut */
    SweepOut: {
      /** Considered */
      considered: number;
      /** Drafted */
      drafted: number;
      /** Already Had One */
      already_had_one: number;
    };
    /** TailorOut */
    TailorOut: {
      artifact: components["schemas"]["ArtifactSummary"];
      /** Model */
      model: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  me_read_me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Me"];
        };
      };
    };
  };
  profile_get_profile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProfileOut"];
        };
      };
      /** @description No usable credentials were presented. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
    };
  };
  profile_update_profile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProfileUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProfileOut"];
        };
      };
      /** @description No usable credentials were presented. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  profile_add_item: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ItemIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ItemOut"];
        };
      };
      /** @description No usable credentials were presented. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  profile_delete_item: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        item_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No usable credentials were presented. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /**
       * @description The resource does not exist, or belongs to someone else.
       *
       *         Those two cases return the same response on purpose. A 403 for a row owned by
       *         another user would confirm that the row exists, which is a membership oracle over
       *         other people's data.
       */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  profile_update_item: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        item_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ItemPatch"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ItemOut"];
        };
      };
      /** @description No usable credentials were presented. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /**
       * @description The resource does not exist, or belongs to someone else.
       *
       *         Those two cases return the same response on purpose. A 403 for a row owned by
       *         another user would confirm that the row exists, which is a membership oracle over
       *         other people's data.
       */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  profile_review_all: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProfileOut"];
        };
      };
      /** @description No usable credentials were presented. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
    };
  };
  profile_import_resume: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_profile_import_resume"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportOut"];
        };
      };
      /**
       * @description The input was well-formed but could not be used.
       *
       *         A link to a board with no adapter, a posting that has been taken down, a paste
       *         too short to be a description. The detail is written to be shown to the person
       *         who typed it, because in every one of those cases they are the one who can fix it.
       */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description No usable credentials were presented. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  jobs_list_jobs: {
    parameters: {
      query?: {
        status?: components["schemas"]["JobStatus"] | null;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JobSummary"][];
        };
      };
      /** @description No usable credentials were presented. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  jobs_save_job: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SaveJob"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SavedJob"];
        };
      };
      /**
       * @description The input was well-formed but could not be used.
       *
       *         A link to a board with no adapter, a posting that has been taken down, a paste
       *         too short to be a description. The detail is written to be shown to the person
       *         who typed it, because in every one of those cases they are the one who can fix it.
       */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description No usable credentials were presented. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  jobs_get_job: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JobDetail"];
        };
      };
      /** @description No usable credentials were presented. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /**
       * @description The resource does not exist, or belongs to someone else.
       *
       *         Those two cases return the same response on purpose. A 403 for a row owned by
       *         another user would confirm that the row exists, which is a membership oracle over
       *         other people's data.
       */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  jobs_get_score: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ScoreOut"];
        };
      };
      /** @description No usable credentials were presented. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /**
       * @description The resource does not exist, or belongs to someone else.
       *
       *         Those two cases return the same response on purpose. A 403 for a row owned by
       *         another user would confirm that the row exists, which is a membership oracle over
       *         other people's data.
       */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  jobs_retry_job: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SavedJob"];
        };
      };
      /** @description No usable credentials were presented. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /**
       * @description The resource does not exist, or belongs to someone else.
       *
       *         Those two cases return the same response on purpose. A 403 for a row owned by
       *         another user would confirm that the row exists, which is a membership oracle over
       *         other people's data.
       */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  applications_get_board: {
    parameters: {
      query?: {
        include_closed?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Board"];
        };
      };
      /** @description No usable credentials were presented. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  applications_start_application: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["StartApplication"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationDetail"];
        };
      };
      /** @description No usable credentials were presented. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /**
       * @description The resource does not exist, or belongs to someone else.
       *
       *         Those two cases return the same response on purpose. A 403 for a row owned by
       *         another user would confirm that the row exists, which is a membership oracle over
       *         other people's data.
       */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description The request contradicts the current state, such as an illegal stage change. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  applications_get_application: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        application_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationDetail"];
        };
      };
      /** @description No usable credentials were presented. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /**
       * @description The resource does not exist, or belongs to someone else.
       *
       *         Those two cases return the same response on purpose. A 403 for a row owned by
       *         another user would confirm that the row exists, which is a membership oracle over
       *         other people's data.
       */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  applications_delete_application: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        application_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No usable credentials were presented. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /**
       * @description The resource does not exist, or belongs to someone else.
       *
       *         Those two cases return the same response on purpose. A 403 for a row owned by
       *         another user would confirm that the row exists, which is a membership oracle over
       *         other people's data.
       */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  applications_move_stage: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        application_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MoveStage"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationDetail"];
        };
      };
      /** @description No usable credentials were presented. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /**
       * @description The resource does not exist, or belongs to someone else.
       *
       *         Those two cases return the same response on purpose. A 403 for a row owned by
       *         another user would confirm that the row exists, which is a membership oracle over
       *         other people's data.
       */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description The request contradicts the current state, such as an illegal stage change. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  documents_tailor: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        application_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TailorOut"];
        };
      };
      /**
       * @description The input was well-formed but could not be used.
       *
       *         A link to a board with no adapter, a posting that has been taken down, a paste
       *         too short to be a description. The detail is written to be shown to the person
       *         who typed it, because in every one of those cases they are the one who can fix it.
       */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description No usable credentials were presented. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /**
       * @description The resource does not exist, or belongs to someone else.
       *
       *         Those two cases return the same response on purpose. A 403 for a row owned by
       *         another user would confirm that the row exists, which is a membership oracle over
       *         other people's data.
       */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  documents_list_artifacts: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        application_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ArtifactSummary"][];
        };
      };
      /** @description No usable credentials were presented. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  documents_download: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        artifact_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No usable credentials were presented. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /**
       * @description The resource does not exist, or belongs to someone else.
       *
       *         Those two cases return the same response on purpose. A 403 for a row owned by
       *         another user would confirm that the row exists, which is a membership oracle over
       *         other people's data.
       */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  documents_list_nudges: {
    parameters: {
      query?: {
        include_dismissed?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["NudgeOut"][];
        };
      };
      /** @description No usable credentials were presented. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  documents_update_nudge: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        nudge_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["NudgeUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["NudgeOut"];
        };
      };
      /** @description No usable credentials were presented. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /**
       * @description The resource does not exist, or belongs to someone else.
       *
       *         Those two cases return the same response on purpose. A 403 for a row owned by
       *         another user would confirm that the row exists, which is a membership oracle over
       *         other people's data.
       */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  documents_sweep: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SweepOut"];
        };
      };
      /** @description No usable credentials were presented. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description The request contradicts the current state, such as an illegal stage change. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
    };
  };
  health_healthz: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Health"];
        };
      };
    };
  };
}
